apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: asset-parameters-summary-service-deploy
spec:
  serviceName: "asset-parameters-summary-service"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: asset-parameters-summary-service
  template:
    metadata:
      labels:
        app: asset-parameters-summary-service
      annotations:
        version: "20181205.1"
    spec:
      containers:
      - name: asset-parameters-summary-service
        image: ahck8s.azurecr.io/apm-asset-parameters-summary-service:20181205.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupParametersSummaryService
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicParameters
        - name: STORE
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: storeType
        - name: STORE_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: storeconfiguration
        - name: REPLICAS
          value: "1"
        - name: POD_NAME_PREFIX
          value: "asset-parameters-summary-service-deploy"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      nodeSelector:
         beta.kubernetes.io/os: linux 
      imagePullSecrets:
        - name: ahc-repository