apiVersion: v1
kind: Secret
metadata:
  name: tenant-secrets
type: Opaque
data:
  busconfiguration: <BUS_CONFIGURATION_BASE64>
  storeconfiguration: <STORE_CONFIGURATION_BASE64>
  sqlconnectionstring: <SQL_CONNECTIONSTRING_BASE64>
  adApplicationSecretKey: <APPLICATION_SECRET_KEY_BASE64>
  notificationEmailServerPassword: <NOTIFICATION_EMAIL_SERVER_PASSWORD>