apiVersion: v1
kind: Service
metadata:
  name: api-translationservice
spec:
  selector:
    app: api-translationservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-translationservice-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api-translationservice
      annotations:
        version: "20181206.1"
    spec:
      containers:
      - name: api-translationservice
        image: ahck8s.azurecr.io/api-translationservice:20181206.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: environmentName
        - name: APP_INSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: appInsightsInstrumenationKey
        - name: CACHE_EXPIRATION_IN_MINUTES
          value: "15"
      nodeSelector:
         beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: ahc-repository