apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
data:
  environmentName: <ENVIRONMENT_NAME>
  tenant: <TENANT_NAME>
  busType: <BUS_TYPE>
  storeType: <STORE_TYPE>
  appInsightsInstrumenationKey: <APP_INSIGHTS_INSTRUMENTATION_KEY>
  adApplicationId: <AAD_APPLICATION_ID>
  topicRawData: raw-data
  topicTriggers: "triggers"
  topicModelIssueMessages: model-issue-messages
  topicEventChanges: event-changes
  topicParameters: parameters
  topicModelMessageLog: model-message-log
  topicModelParameters: model-parameters
  topicModelInputs: model-inputs
  topicModelOutput: model-outputs
  topicModelIssues: model-issues
  topicHealthScores: health-scores
  topicModelCustomOutputs: model-custom-outputs
  topicNotifications: notifications
  topicRisks: risks
  topicAssetHistory: asset-history
  consumerGroupModelRouter: model-router-service
  consumerGroupDataRouter: data-router-service
  consumerGroupModelExecutor: model-executor-service
  consumerGroupModelOutput: model-output-service
  consumerGroupParameters: "parameters-service-{0}"
  consumerGroupParametersSql: "parameters-service-sql-{0}"
  consumerGroupParametersSummaryService: "parameters-summary-service-{0}"
  consumerGroupReplacementScoreService: "replacement-score-service-{0}"
  consumerGroupModelInputCollector: "model-input-collector-service-{0}"
  consumerGroupAssetIssue: "issue-service-{0}"
  consumerGroupAssetIssueTriggerService: issue-trigger-service
  consumerGroupModelMessages: message-service
  consumerGroupScoreService: "score-service-{0}"
  consumerGroupNotifications: notification-service
  consumerGroupRiskService: "risk-service-{0}"
  consumerGroupAssetHistoryService: "asset-history-service-{0}"
  consumerGroupMaintenanceScoreService: maintenance-score-service
  consumerGroupAssetSpatialViewService: asset-spatial-view-service
  consumerGroupRiskTrendService: risk-trend-service
  consumerGroupAssetRiskSummaryService: asset-risk-summary-service
  consumerGroupCustomModelOutputsService: "custom-model-outputs-service-{0}"
  urlUserService: "http://api-userservice.<ENVIRONMENT_NAME>:8080"
  urlCustomerService: "http://api-customerservice.<ENVIRONMENT_NAME>:8080"
  urlTranslationService: "http://api-translationservice.<ENVIRONMENT_NAME>:8080"
  parametersHistorySize: "1000"
  scoresHistorySize: "2000"
  modelTriggerExecutionDelayInSecends: "10"
  notificationAlertEmailAddress: <NOTIFICATION_ALERT_EMAIL_ADDRESS>
  notificationEmailServer: <NOTIFICATION_EMAIL_SERVER>
  notificationEmailServerPort: "<NOTIFICATION_EMAIL_SERVER_PORT>"
  notificationEmailServerUsername: <NOTIFICATION_EMAIL_SERVER_USERNAME>
  notificationEmailServerEnableSsl: "<NOTIFICATION_EMAIL_SERVER_ENABLE_SSL>"
  applicationWebsiteUrl: <APPLICATION_WEBSITE_URL>