apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modelsdata-router-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: modelsdata-router
      annotations:
        version: "20181206.1"
    spec:
      containers:
      - name: modelsdata-router
        image: ahck8s.azurecr.io/apm-modelsdatarouter:20181206.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupModelRouter
        - name: SOURCE
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicParameters
        - name: TARGET
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicModelParameters
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: STORE
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: storeType
        - name: STORE_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: storeconfiguration
        - name: SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: sqlconnectionstring
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
      nodeSelector:
         beta.kubernetes.io/os: linux 
      imagePullSecrets:
        - name: ahc-repository