apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asset-spatial-view-service-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: asset-spatial-view-service
      annotations:
        version: "20181113.2"
    spec:
      containers:
      - name: asset-spatial-view-service
        image: ahck8s.azurecr.io/apm-asset-spatial-view-service:20181113.2
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupAssetSpatialViewService
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
        - name: SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: sqlconnectionstring
        - name: TRIGGER_TOPIC
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicTriggers
      nodeSelector:
         beta.kubernetes.io/os: linux 
      imagePullSecrets:
        - name: ahc-repository