apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apm-custom-model-outputs-service-deploy
spec:
  serviceName: "apm-custom-model-outputs-service"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: apm-custom-model-outputs-service
  template:
            fieldRef:
              fieldPath: metadata.name
         - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupCustomModelOutputsService
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
        - name: SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: sqlconnectionstring
        - name: MODEL_CUSTOM_OUTPUTS_TOPIC
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicModelCustomOutputs
      nodeSelector:
         beta.kubernetes.io/os: linux 
      imagePullSecrets:
        - name: ahc-repository