apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model-executor-linux-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: model-executor-linux
      annotations:
        version: "20181204.1"
    spec:
      containers:
      - name: model-executor-linux
        image: ahck8s.azurecr.io/apm-model-executor-linux:20181204.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupModelExecutor
        - name: SOURCE
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicModelInputs
        - name: TARGET
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicModelOutput
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
        - name: MODELS_FOLDER
          value: "Models"
      nodeSelector:
         beta.kubernetes.io/os: linux 
      imagePullSecrets:
        - name: ahc-repository