apiVersion: v1
kind: Service
metadata:
  name: api-customerservice
spec:
  selector:
    app: api-customerservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-customerservice-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api-customerservice
      annotations:
        version: "20181130.2"
    spec:
      containers:
      - name: api-customerservice
        image: ahck8s.azurecr.io/api-customerservice:20181130.2
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: environmentName
        - name: APP_INSIGHTS_INSTRUMENTATION_KEY
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: appInsightsInstrumenationKey
        - name: CACHE_EXPIRATION_IN_MINUTES
          value: "60"
        - name: KEY_VAULT_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: keyVaultApplicationKey
        - name: KEY_VAULT_APPLICATION_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: keyVaultApplicationId
        - name: KEY_VAULT_KEY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: keyVaultKeyAddress
        - name: STORE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: storeType
        - name: STORE_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: common-secrets
              key: storeconfiguration
        - name: CUSTOMERS_CONTAINER
          value: "customers"
      nodeSelector:
         beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: ahc-repository