apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: replacementscore-service-deploy
spec:
  serviceName: "replacementscore-service"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: replacementscore-service
  template:
    metadata:
      labels:
        app: replacementscore-service
      annotations:
        version: "20181119.1"
    spec:
      containers:
      - name: replacementscore-service
        image: ahck8s.azurecr.io/apm-replacementscore-service:20181119.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: environmentName
        - name: BUS
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: busType
        - name: BUS_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: busconfiguration
        - name: BUS_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: consumerGroupReplacementScoreService
        - name: TENANT
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: tenant
        - name: TOPIC_FOR_DEGRADATIONSCORE
          valueFrom:
            configMapKeyRef:
              name: tenant-config
              key: topicHealthScores
        - name: SQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: sqlconnectionstring
        - name: REPLICAS
          value: "1"
        - name: POD_NAME_PREFIX
          value: "replacementscore-service-deploy"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      nodeSelector:
         beta.kubernetes.io/os: linux
      imagePullSecrets:
        - name: ahc-repository